/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_camera_test_CameraView */

#ifndef _Included_com_camera_test_CameraView
#define _Included_com_camera_test_CameraView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_camera_test_CameraView
 * Method:    IsBlink
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_com_camera_test_CameraView_IsBlink
  (JNIEnv *, jclass, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
